Repository ansible-middleware/wildfly, pull requests merged in 2022-11, with the labels that each got.

#89 Update disable_repo.yml
  roles/wildfly_subs/tasks/disable_repo.yml
Labels: documentation

#90 wildfly_install: (eap) apply_cp does not depend on systemd
  roles/wildfly_install/README.md
  roles/wildfly_install/defaults/main.yml
  roles/wildfly_install/meta/argument_specs.yml
  roles/wildfly_install/tasks/install.yml
  roles/wildfly_install/tasks/prereqs.yml
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/meta/argument_specs.yml
  roles/wildfly_systemd/vars/main.yml
Labels: major_changes

#91 wildfly-systemd: yaml configuration extension accept templates
  molecule/yaml_config_validation/converge.yml
  molecule/yaml_config_validation/prepare.yml
  molecule/yaml_config_validation/templates/dummy_yaml_configuration.yml.j2
  molecule/yaml_config_validation/templates/wildfly_yaml_configuration.yml
  molecule/yaml_config_validation/vars.yml
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/tasks/yml_config.yml
  roles/wildfly_systemd/templates/wfly.conf.j2
Labels: minor_changes

#92 Add elytron adapter install (EAP)
  roles/wildfly_install/meta/argument_specs.yml
  roles/wildfly_install/tasks/install.yml
  roles/wildfly_utils/tasks/keycloak_adapter.yml
Labels: minor_changes
