Repository ansible-middleware/wildfly, pull requests merged in 2024-08, with the labels that each got.

#251 Update jboss_cli.yml - conditional statements variable adjustment
  roles/wildfly_utils/tasks/jboss_cli.yml
Labels: next_eap_release

#250 Using local path variable for offline installation.
  roles/wildfly_install/tasks/prereqs.yml
Labels: next_eap_release

#258 [#257] Remove legacy redundant TCPPING configuration & define whole topology in TCPPING
  molecule/colocated_cluster/converge.yml
  molecule/colocated_cluster/templates/configure_tcp_ping.yml.j2
  molecule/colocated_cluster/templates/yaml_configuration.yml.j2
Labels: next_eap_release

#262 Issue249
  roles/wildfly_install/defaults/main.yml
  roles/wildfly_install/tasks/prereqs.yml
Labels: bugfixes, minor_changes

#263 Add functionality to allow EAP QE PRE GA testing
  molecule/colocated_cluster/molecule.yml
  molecule/custom_config_file/molecule.yml
  molecule/default/molecule.yml
  molecule/group_vars/all/vars.yml
  molecule/install_options/molecule.yml
  molecule/prepare.yml
  molecule/prospero/molecule.yml
  molecule/resources/download_asset.yml
  molecule/resources/download_assets.yml
  molecule/resources/download_pre_ga_bits.yml
  molecule/uninstall/molecule.yml
  molecule/yaml_config_validation/molecule.yml
Labels: minor_changes

#265 Update all molecule scenario to use UBI9 instead of UBI8
  molecule/custom_config_file/molecule.yml
  molecule/default/molecule.yml
  molecule/install_options/molecule.yml
  molecule/uninstall/molecule.yml
  molecule/yaml_config_validation/molecule.yml
Labels: minor_changes
