Repository ansible-middleware/wildfly, pull requests merged in 2024-04, with the labels that each got.

#207 Add wait_for logic in systemd unit
  roles/wildfly_install/defaults/main.yml
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/meta/argument_specs.yml
  roles/wildfly_systemd/tasks/service.yml
  roles/wildfly_systemd/templates/wfly.service.j2
Labels: minor_changes

#211 Add wildfly_validation logic for colocated cluster
  .github/workflows/ci.yml
  molecule/colocated_cluster/converge.yml
  molecule/colocated_cluster/molecule.yml
  molecule/colocated_cluster/verify.yml
  molecule/colocatedds/converge.yml
  molecule/colocatedds/molecule.yml
  molecule/colocatedds/verify.yml
  molecule/prepare.yml
  playbooks/test.yml
  roles/wildfly_migration/defaults/main.yml
  roles/wildfly_validation/defaults/main.yml
  roles/wildfly_validation/tasks/logfile.yml
  roles/wildfly_validation/tasks/main.yml
Labels: enhancement, minor_changes

#210 Fix wildfly_install changing ownership of system directories
  roles/wildfly_install/tasks/main.yml
Labels: bugfixes

#217 Skip pidfile validation
  roles/wildfly_validation/tasks/main.yml
  roles/wildfly_validation/tasks/pidfile_validate.yml
  roles/wildfly_validation/tasks/systemd.yml
Labels: enhancement, minor_changes

#221 App deploy to trigger cluster formation and verification (upstream CI only)
  molecule/colocated_cluster/converge.yml
  molecule/colocated_cluster/verify.yml
Labels: minor_changes

#216 install: allow user to change path on controller to store zips
  roles/wildfly_install/tasks/install.yml
  roles/wildfly_validation/defaults/main.yml
  roles/wildfly_validation/meta/argument_specs.yml
  roles/wildfly_validation/tasks/systemd.yml
Labels: minor_changes

#226 use own config directory for colocated instances
  roles/wildfly_systemd/tasks/main.yml
  roles/wildfly_systemd/tasks/pid_config.yml
  roles/wildfly_systemd/tasks/systemd.yml
  roles/wildfly_systemd/templates/wfly.conf.j2
  roles/wildfly_utils/tasks/keycloak_adapter.yml
Labels: bugfixes

#239 Use prospero 1.3.0.Beta1
  molecule/uninstall/vars.yml
  roles/wildfly_driver/README.md
  roles/wildfly_driver/defaults/main.yml
  roles/wildfly_driver/meta/argument_specs.yml
  roles/wildfly_install/README.md
  roles/wildfly_install/defaults/main.yml
  roles/wildfly_install/meta/argument_specs.yml
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/meta/argument_specs.yml
  roles/wildfly_uninstall/README.md
  roles/wildfly_utils/README.md
  roles/wildfly_utils/defaults/main.yml
  roles/wildfly_utils/meta/argument_specs.yml
  roles/wildfly_utils/tasks/prospero/main.yml
  roles/wildfly_validation/defaults/main.yml
  roles/wildfly_validation/meta/argument_specs.yml
Labels: bugfixes, enhancement
