Repository ansible-middleware/wildfly, pull requests merged in 2024-03, with the labels that each got.

#181 Enable Prospero molecule scenario to run
  molecule/prospero/converge.yml
  molecule/prospero/prepare.yml
Labels: minor_changes

#188 Cleanup systemd role by breaking apart main.yml
  roles/wildfly_systemd/tasks/apply_cp.yml
  roles/wildfly_systemd/tasks/instance_name.yml
  roles/wildfly_systemd/tasks/main.yml
  roles/wildfly_systemd/tasks/systemd.yml
Labels: minor_changes

#192 Allow to use different names for nodeId, instance name, systemd unit name
  .ansible-lint
  .github/workflows/ci.yml
  molecule/colocated/converge.yml
  molecule/colocated/molecule.yml
  molecule/colocated/prepare.yml
  molecule/colocated/verify.yml
  playbooks/playbook.yml
  playbooks/validate.yml
  roles/wildfly_install/defaults/main.yml
  roles/wildfly_install/meta/argument_specs.yml
  roles/wildfly_install/tasks/install.yml
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/meta/argument_specs.yml
  roles/wildfly_systemd/tasks/apply_cp.yml
  roles/wildfly_systemd/tasks/instance_name.yml
  roles/wildfly_systemd/tasks/main.yml
  roles/wildfly_systemd/tasks/service.yml
  roles/wildfly_systemd/tasks/systemd.yml
  roles/wildfly_systemd/tasks/yml_config.yml
  roles/wildfly_systemd/tasks/yml_config_version_prereq.yml
  roles/wildfly_systemd/templates/wfly.conf.j2
  roles/wildfly_systemd/templates/wfly.service.j2
  roles/wildfly_uninstall/tasks/main.yml
  roles/wildfly_utils/tasks/apply_cp.yml
  roles/wildfly_utils/tasks/keycloak_adapter.yml
  roles/wildfly_validation/tasks/verify_owner_and_group.yml
  roles/wildfly_validation/tasks/verify_with_cli_queries.yml
Labels: minor_changes

#195 Validate `wildfly_node_id` length and default to `inventory_hostname_short`
  roles/wildfly_install/tasks/prereqs.yml
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/meta/argument_specs.yml
  roles/wildfly_systemd/tasks/main.yml
Labels: minor_changes

#199 molecule: bump cluster to 3 node in colocated scenario
  molecule/colocated/converge.yml
  molecule/colocated/verify.yml
Labels: enhancement

#200 prospero: update README and remove duplicated call to wildfly_user
  molecule/prospero/converge.yml
  roles/wildfly_prospero/README.md
Labels: documentation, minor_changes

#190 Set pid file for systemd to /var/run/{{ instance }} or allow for custom pid file location
  roles/wildfly_systemd/README.md
  roles/wildfly_systemd/defaults/main.yml
  roles/wildfly_systemd/handlers/main.yml
  roles/wildfly_systemd/tasks/main.yml
  roles/wildfly_systemd/tasks/pid_config.yml
  roles/wildfly_systemd/templates/wfly.conf.j2
  roles/wildfly_systemd/templates/wfly.service.j2
  roles/wildfly_systemd/vars/main.yml
  roles/wildfly_validation/defaults/main.yml
  roles/wildfly_validation/tasks/pidfile_validate.yml
Labels: enhancement, major_changes

#203 JBoss EAP 7.4.7+ patching fails on openjdk17 if elytron is not enabled
  roles/wildfly_systemd/vars/main.yml
  roles/wildfly_utils/meta/argument_specs.yml
  roles/wildfly_utils/tasks/apply_cp.yml
  roles/wildfly_utils/tasks/jboss_cli.yml
Labels: bugfixes
